# Generated by Django 2.0.7 on 2020-07-17 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200717_0539'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='etc',
            field=models.TextField(default='hello'),
            preserve_default=False,
        ),
    ]
