# Generated by Django 2.0.7 on 2020-07-17 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_etc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='des'),
            preserve_default=False,
        ),
    ]
